language: php
php:
- 7.1
- 7.2
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- TRAVIS_NODE_VERSION="8"
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install -g yarn
- yarn
- composer install
- ulimit -n 4096
script:
- yarn run build:production
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kytAZC6PdgL0tbMyl1wlFTn+XR512QFnkq1IAzlYiB5hKqYKv8jLuj5qsq9izUsEjsksSyIllKmyfVW/P1W/1EDNMBcsxlDYFldERf1K2XJbNhoOHn/JETuJ7gi1GHdsqUPcDTx0DOICJOFlNP84YnSWSf+xl4q5ezlsj/NZT3lqGfaxQwFmnBlXgHZxnYOveaoz0IYfUFvWrbWqVWHbZDWbB7dHCUYTLpgIoJop8Rhuc1MEDUMW6E3R3SONbdP8rFb/mfD3nRN1o/nCBthNtf9fL0rfLRaYMc1t7ckvZxj9uLmvi3DzRRr9m8+Erg+tKDL72UAY5Wvjv9i2ve2uzkEh4CAaamy3bR/gR0nurf25kwOrBzMZKAmmsbbIS0YMcE7rmdK+5id3jGT3w3PpONFDZdSnhGKVOsBTyf2CmVBGurfBp9j/T2VPWZMVNi2+ErTWUgcLl5Y6i5GWM5SyHq3CkZOi5Opr1XP+qxKXO8Nn42l2D9EBWNRRZ7dTMkiBBnJtYZdFgnMox4/3ogiqeY3ThjXthw5uYJAuxw2YSnmds7xn010lpl66uQIbRQbGkJJERuhhfvoDkn5uKkbkQpuNHSactNrVe0MlqC7rEPa91LjOIpTHbwDD7OQ2ozaT/cz7/aao7ljl+Z7bP9oIQLYZrTIb0zAn/XMu8MDH6Qc=
  file: opentextbooks-$TRAVIS_TAG.zip
  on:
    tags: true    
    repo: BCcampus/opentextbooks
    branch: dev
