language: php
php:
- 7.0
- 7.1
- 7.2
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
- TRAVIS_NODE_VERSION="8"
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- sudo apt-get -qq update
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install -g yarn
- yarn
- composer install
- ulimit -n 4096
script:
- yarn run build:production
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: tbjtsVQQosro4zeLn6iFSyq1kpaS0Ywe1r/QRsj9IEx5Mqp80pAg6UMZ+lVpViiEtKkq/J7qTJYqhlbwS3u1RoiDi25cVA/Pwc9wE8iTTYmDggB3I6zmVN+P1WBJ4i8uNYuZRuCvq1yKBI0GuPx158lANsStuZ+BhN9vHinLjL1v78sSDiXp4bTQ3RPNSj80Cgdh9d6rgQEOAThELic7ddcdMxrUgKL7mH8PqXrfRM6PEOABqgmCwWQFLqKSWLDJS9VgHCKcBkSFyDou0lYj1xO4cLWZxoVGDPmRnLQ9teHLePQA8ZpeI+k9NCEJZvY0va64HigvURUPhfDtRMRemBKcHjG7x50CcjBCZ871e0lpfTH0wJ33SX0cNHEdlK84oTG0WBjIRb8bwA1wCT3l/OA7L7GjDHGN9QKaRkP1pR1MQ+vbjr5QxFVhKiGTweYUMZ3X5P23lFJoOr3nMN0xTg9BQona8MIKvitDfKufhS3ZKWONerjPvl2DBnez8kkFK/e+Jk16v5hrQGiu007Nb918ne6LWVvBpvh/6KkGhQ0NMqSBW113+Cbc6ZqJPEg63Y/k0ELrDb4XvwpIRyWFtE0ijuldi5YKba7DuV4sRWx+60qlPsXcpC2y2yfsRWFOJqkEBD6xVptMpoh48nkcrmjtojVf8j4AChuHyUNEh8o=
  file: opentextbooks-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/opentextbooks
    branch: dev
